#!/bin/bash

# Disable `csrutil` before executing this script
# 1. Boot to Recovery OS by restarting your machine and holding down the Command and R keys at startup.
# 2. Launch Terminal from the Utilities menu.
# 3. Enter the following command: `csrutil enable`

Apps=(
  Books
  Calculator
  Chess
  Contacts
  Dashboard
  Dictionary
  FaceTime
  Home
  'Image Capture'
  Maps
  Mail
  Messages
  'Photo Booth'
  Reminders
  Siri
  Stickies
  Stocks
  'Time Machine'
  VoiceMemos
  iTunes
)

for app in "${Apps[@]}"
do
  sudo rm -rf "/Applications/$app.app"
  echo "-$app"
done

